config/routes.rb
Rails.application.routes.draw do
  get 'search' => "searches#search"
  get 'relationships/create'
  get 'relationships/destroy'
  get 'book_comments/create'
  get 'book_comments/destroy'
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments,only:[:create,:destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates :comment,presence:true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      render :comments #render先にjsファイルを指定
    else
      render 'books/show'
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    #renderしたときに@postのデータがないので@postを定義
    @book = Book.find(params[:book_id])  
    render :comments #render先にjsファイルを指定
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [@book, @book_comment],local: false do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに",class: "w-100" %>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_post_comments.html.erb
<table>
    <tbody>
        <% @book.book_comments.each do |book_comment| %>
        <tr>
          <td>
          <%= link_to user_path(book_comment.user) do %>
          <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
          <%= book_comment.user.name %>
          <% end %>
          </td>
          <td><%= book_comment.comment %></td>
          <td>
        <% if @book.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,remote: :true, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
        <% end %>
          </td>
        </tr>
        <% end %>
    </tbody>
 </table>

app/views/book_comments/comments.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/post_comments', book: @book, book_comment: @book_comment) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');