config/routes.rb
Rails.application.routes.draw do
  get 'search' => "searches#search"
  get 'relationships/create'
  get 'relationships/destroy'
  get 'book_comments/create'
  get 'book_comments/destroy'
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments,only:[:create,:destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
    <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range,options_for_select([['User'],['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class:"btn btn-primary" %>
        <% end %>
    </div>
<% end %>

app/views/searches/search.html.erb
<h2>Results index</h2>
<table class="table table-hover table-inverse">
    <% if @range == "User" %>
    <thead>
        <tr>
          <th></th>
          <th>name</th>
          <th>introduction</th>
        </tr>
    </thead>
    
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= link_to user_path(user) do %>
                <%= image_tag user.get_profile_image, size: '50x50' %>
                <% end %>
            </td>
            <td><%= link_to user_path(user) do %><%= user.name %><% end %></td>
            <td><%= user.introduction %></td>
        </tr>
        <% end %>
    </tbody>
    
    
    
    <% else %>
    <thead>
        <tr>
          <th></th>
          <th>title</th>
          <th>opinion</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image, size: '50x50' %>
                <% end %>
            </td>
            <td><%= link_to book_path(book) do %><%= book.title %><% end %></td>
            <td><%= book.body %></td>
        </tr>
        <% end %>
    </tbody>
    <% end %>
</table>